### ISSUE TITLE
Log message in _requestConnection0 has typo

### ISSUE THREAD

**Issue by rausnitz** [vapor/async-kit#107]
### Describe the issue

A parenthesis is missing in a logged error message

### Vapor version

4.102.0

### Operating system and version

macOS

### Swift version

5.10

### Steps to reproduce

See here: https://github.com/vapor/async-kit/blob/bfcc9cb15b41b3138074196503e29ba5a3e4c6e9/Sources/AsyncKit/ConnectionPool/EventLoopConnectionPool.swift#L204

This logs things like
```
Connection request (ID 1 timed out.
```

### Outcome

Change the start of the message to
```
Connection request (ID \(waiterId)) timed out.
```

### Additional notes

I would just open a PR but I wanted to check if this repo is still accepting changes since it's a "legacy" package.

**Comment by 0xTim** [comment]
@rausnitz yep a PR would be great!
