### ISSUE TITLE
.andAllSync

### ISSUE THREAD

**Issue by tanner0101** [vapor/async-kit#18]
Would something like this be useful to add?

```swift
extension EventLoopFuture {
    public static func andAllSync(
        _ futures: [() -> EventLoopFuture<Void>],
        eventLoop: EventLoop
    ) -> EventLoopFuture<Void> {
        ...
    }
}
```

The difference to `.andAll` is that each future is not started until the previous one completes. This is useful for things like database migrations where you must not _start_ the next task until the previous is completed.

**Comment by Mordil** [comment]
Is this valid Swift?

```swift
public static func andAllSync(
    _ futures: [@autoclosure () -> EventLoopFuture<Void>],
    eventLoop: EventLoop
) -> EventLoopFuture<Void> { }
```

**Comment by tanner0101** [comment]
Looks like no. Bummer because I was thinking about that, too.

![screen shot 2019-01-31 at 1 53 20 pm](https://user-images.githubusercontent.com/1342803/52077688-9432f880-255f-11e9-9ae5-48ecd1f6b2ac.png)

**Comment by Mordil** [comment]
Hm. Sounds like an idea to float on the forums...

Overall - this is good. Just some bikeshedding over parameter name and method name.

I'm still trying to resolve what to have the methods be named in SwiftNIO itself with the type of extensions I've been writing for it.

**Comment by tanner0101** [comment]
@Mordil I guess this should wait until the bikeshedding is complete with your proposal, then we can make sure this one follows suit with naming.

**Comment by Mordil** [comment]
If you want to jump in and share your thoughts I brought it up on this thread: https://github.com/apple/swift-nio/issues/184#issuecomment-457649370

**Comment by Mordil** [comment]
@tanner0101 It looks like the proposed names of `andAll{Succeed | Complete}` and `whenAll{Succeed | Complete}` are being accepted in SwiftNIO

**Comment by tanner0101** [comment]
`EventLoopFutureQueue` can now be used to implement this behavior 👍
