### ISSUE TITLE
Future Collection Mapping

### ISSUE THREAD

**Issue by calebkleveter** [vapor/async-kit#2]
Create a `.mapElements` method for `EventLoopFuture<Sequence>` where the callback receives a single element in the sequence instead of the whole sequence:

```swift
let users: Future<[User]> = ...
users.mapElements { user in
    print(user.id)
}
```

**Comment by calebkleveter** [comment]
It is worth seeing if `EventLoopFuture<Sequence>` could be conformed to the `Sequence` protocol. The same for `EventLoopFuture<Collection>` and `Collection`.

**Comment by tanner0101** [comment]
+1 to this. 

> It is worth seeing if EventLoopFuture<Sequence> could be conformed to the Sequence protocol. The same for EventLoopFuture<Collection> and Collection.

Would be interesting, but I bet at least one of those methods requires synchronous access to the results.

One additional thought, what if we had something like `thenElements` where you map each element to a future? This could be a nice combination of `map` + `flatten`, reducing the need for flattening.

```swift
let planets: EventLoopFuture<[Planet]> = ...
let galaxies = planets.thenElements { planet in
    return planet.galaxy.get() // Future<Galaxy>
}
print(galaxies) // EventLoopFuture<[Galaxy]>
```

**Comment by tanner0101** [comment]
Also, using `each` could be a bit more concise and consistent with API like `forEach`.

```swift
let users: Future<[User]> = ...
users.mapEach { user in
    print(user.id)
}
users.thenEach { user in
    print(user.id)
}
```
