### ISSUE TITLE
Feature request: convert DatabaseConnectionPool into a protocol

### ISSUE THREAD

**Issue by MrMage** [vapor/async-kit#23]
I am currently using a custom database connection pool (https://gist.github.com/MrMage/8972472ee73ab7b7d506ffb1c2b6e42e). If the official [`DatabaseConnectionPoool`](https://github.com/vapor/database-kit/blob/master/Sources/DatabaseKit/ConnectionPool/DatabaseConnectionPool.swift) was implemented as a protocol, I could more easily swap the regular one out with my own implementation.

The only problem might be associated type requirements for that protocol (currently the class has a generic `Database` type argument), but I think that could be worked around.

**Comment by tanner0101** [comment]
I've transferred the issue to NIOKit, since that's where `ConnectionPool` lives now. 

I think this issue might actually pertain more to Fluent or Vapor though. Where are you attempting to plug this special case connection pool into?

**Comment by MrMage** [comment]
The idea is to have a connection pool that can temporarily scale up the number of open connections to keep latency low, but automatically closes unused connections over time after a while to avoid hitting PostgreSQL's fairly low connection limit. This is used in place of the regular connection pool by my request handlers. (I think we briefly discussed this in person at November's Swift Cloud workshop in NYC.)

Hope that makes sense; let me know if you have further questions.

**Comment by tanner0101** [comment]
@MrMage I think that will be possible in Fluent 4 by creating a custom `AutoScalingPool` type and conforming that to `FluentDatabase`. You would then register that instead of the default connection pool to your database config. Your controllers would all continue to depend on `FluentDatabase` without noticing a change.

**Comment by MrMage** [comment]
Sounds good! I'll look into that (and might ask you more about the details) once I migrate to Fluent 4. I assume that `FluentDatabase` in Fluent 4 is some kind of protocol that can be fulfilled by the connection pool instead of a concrete connection?

In a similar vein, how easy would it be in Fluent 4 to only reserve a connection for each individual database query instead of for the entire lifetime of the current request? Or will that be the default?

**Comment by tanner0101** [comment]
> `FluentDatabase` in Fluent 4 is some kind of protocol that can be fulfilled by the connection pool instead of a concrete connection

Anything that conforms to `FluentDatabase` can be used to do Fluent queries. i.e.:

```swift
let db: FluentDatabase ...
Model.query(on: db.)...
user.save(on: db)
```

By default, databases will register a connection pool as their conformer, but you could register anything you want, including dummy DBs for testing.

> how easy would it be in Fluent 4 to only reserve a connection for each individual database query instead of for the entire lifetime of the current request

Yup, that will be the default going forward.

**Comment by MrMage** [comment]
Thanks for the explanation! Thinking about this more, given that `Pool.available` is a LIFO stack, creating a connection type that automatically self-closes if it hasn't been used for eg 60 seconds could achieve the same effect. Would creating a wrapper around a regular connection that adds this behavior (and forwards everything else to the wrapped connection) be possible for me to implement with Fluent 4?

**Comment by tanner0101** [comment]
Yes, it would work via the same mechanism (creating a custom `FluentDatabase`). For this case, you'd probably want to wrap the base connection (i.e., `PostgresConnection`) in something like a  `SelfClosingConnection<C>`  wrapper. Then you'd initialize a pool and FluentDatabase from that, registering it as the same identifier (i.e., .psql). All of your application code that relies on the `.psql` Fluent database would then start using the DB w/ the self-closing logic.

**Comment by MrMage** [comment]
I still think that there would be value to being able to provide custom implementations of `ConnectionPool`. However, I guess a protocol would not be ideal due because the pool is a generic. How about a base `AbstractConnectionPool` instead whose methods users could implement themselves?

Also, I hardly see anything specific to _Connections_ in https://github.com/vapor/async-kit/blob/master/Sources/AsyncKit/ConnectionPool.swift besides `isClosed`/`close()`, and those could even be relevant to other types of resources as well. Why not rename it to e.g. `ResourcePool`?

**Comment by tanner0101** [comment]
I think a connection pool protocols would make sense at a higher layer. For example, Fluent, which already has the `Database` protocol for abstracting this behavior. AsyncKit is providing a specific type of connection pool implementation for a specific use case. Any packages that want to use this pool can abstract it if needed.
