### ISSUE TITLE
Request: Add a timeout for waiting on pooled connections

### ISSUE THREAD

**Issue by MrMage** [vapor/async-kit#38]
There should be an option to automatically fail a future returned by `requestConnection` after, say, 15 seconds if the pool is still exhausted after the end of the timeout. This would be another option to eliminate the deadlock described in https://github.com/vapor/nio-kit/blob/master/Sources/NIOKit/ConnectionPool.swift; one request would fail after waiting too long, allowing all others to proceed.

**Comment by MrLotU** [comment]
Fixed per #67
