### ISSUE TITLE
Renaming the variadic maps to zip

### ISSUE THREAD

**Issue by John-Connolly** [vapor/async-kit#4]
Just a thought, it would be more inline with rx 
``` swift 

public func map<A, B, Result>(
    to result: Result.Type,
    _ futureA: Future<A>,
    _ futureB: Future<B>,
    _ callback: @escaping (A, B) throws -> (Result)
) -> Future<Result> {
    return futureA.flatMap(to: Result.self) { a in
        return futureB.map(to: Result.self) { b in
            return try callback(a, b)
        }
    }
}

```
vs

``` swift
public func zip<A, B, Result>(
    to result: Result.Type,
    _ futureA: Future<A>,
    _ futureB: Future<B>,
    _ callback: @escaping (A, B) throws -> (Result)
) -> Future<Result> {
    return futureA.flatMap(to: Result.self) { a in
        return futureB.map(to: Result.self) { b in
            return try callback(a, b)
        }
    }
}

```

**Comment by calebkleveter** [comment]
+ 1 to this. Not only would it match Rx better (I'm taking your word for that 😄), but that matches the standard Swift API better with their `zip` method for sequences.

**Comment by tanner0101** [comment]
I kind of prefer Swift NIO's solution to this:

```swift
futureA.and(futureB).and(futureC).then { ... }
```

It doesn't have the same restrictions as `map` / `zip`.

**Comment by John-Connolly** [comment]
Yeah true thats better saves a bunch of code.

**Comment by calebkleveter** [comment]
@tanner0101 One thing I don't like about `.and` is that you end up with deep nesting and it's a pain to deconstruct:

```swift
future1.and(future2).and(future3).and(future4).map { futures in
    let four = futures.1.1.1
}
```

I wish you could deconstruct tuples in closure arguments, but you can't and it sounds like it was a [conscious decision not to](https://bugs.swift.org/browse/SR-4738?focusedCommentId=24311&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24311). Maybe someone could propose and implement it though.

**Comment by tanner0101** [comment]
@calebkleveter i agree. It's annoying. This is definitely Swift's fault IMO. I still think the trade off of not polluting the source code with a ton of variadic overloads is worth it though.

Maybe someone from the Swift or NIO team has an idea on how to get an API better than `futures.1.1.1`?
