### ISSUE TITLE
testPerformance hangs in release mode

### ISSUE THREAD

**Issue by glbrntt** [vapor/async-kit#45]
`testPerformance` never completes in release mode: a connection pool with a maximum of two connections is created but then three connections are requested and waited on:

```
let connA = try! pool.requestConnection().wait()
let connB = try! pool.requestConnection().wait()
let connC = try! pool.requestConnection().wait()
```

Either `connA` or `connB` need to be released for the `connC` future to be resolved.

### Steps to reproduce

1. run `testPerformance` in release mode

### Expected behavior

`testPerformance` completes.

### Actual behavior

`testPerformance` doesn't complete.

### Environment

* NIOKit version: 199a53542275466d691767b63a80ed8e97f52e40
* Linux or macOS? macOS

**Comment by tanner0101** [comment]
Oops. Nice catch, thank you!
